version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "Buildpack to deploy Promscale, the binding between Prometheus and TimescaleDB"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
